{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_DOUBLE","val":-0.26},
		{"id":"PARAM_EYE_R_DOUBLE","val":-0.27},
		{"id":"PARAM_BROW_L_Y","val":-0.15},
		{"id":"PARAM_BROW_R_Y","val":-0.15},
		{"id":"PARAM_BROW_L_ANGLE","val":-0.5},
		{"id":"PARAM_BROW_R_ANGLE","val":-0.5},
		{"id":"PARAM_BROW_L_FORM","val":-0.4},
		{"id":"PARAM_BROW_R_FORM","val":-0.4},
		{"id":"PARAM_MOUTH_FORM_01","val":-0.18,"def":1}
	]
}