{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_OPEN","val":1.15,"calc":"mult"},
		{"id":"PARAM_EYE_L_SMILE","val":1},
		{"id":"PARAM_EYE_R_OPEN","val":1.16,"calc":"mult"},
		{"id":"PARAM_EYE_R_SMILE","val":1},
		{"id":"PARAM_BROW_L_Y","val":-0.22},
		{"id":"PARAM_BROW_R_Y","val":-0.22},
		{"id":"PARAM_BROW_L_ANGLE","val":0.5},
		{"id":"PARAM_BROW_R_ANGLE","val":0.5},
		{"id":"PARAM_MOUTH_FORM_02","val":1}
	]
}