{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_OPEN","val":0.82,"calc":"mult"},
		{"id":"PARAM_EYE_R_OPEN","val":0.82,"calc":"mult"},
		{"id":"PARAM_EYE_FORM","val":0.65},
		{"id":"PARAM_BROW_L_ANGLE","val":-0.48},
		{"id":"PARAM_BROW_R_ANGLE","val":-0.45},
		{"id":"PARAM_BROW_L_FORM","val":-0.71},
		{"id":"PARAM_BROW_R_FORM","val":-0.71},
		{"id":"PARAM_MOUTH_SCALE","val":-0.29}
	]
}