{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_DOUBLE","val":-0.77},
		{"id":"PARAM_EYE_R_DOUBLE","val":-0.74},
		{"id":"PARAM_BROW_L_Y","val":0.19},
		{"id":"PARAM_BROW_R_Y","val":0.18},
		{"id":"PARAM_BROW_L_FORM","val":-0.5},
		{"id":"PARAM_BROW_R_FORM","val":-0.5},
		{"id":"PARAM_MOUTH_FORM_01","val":-1,"def":1},
		{"id":"PARAM_MOUTH_FORM_02","val":1}
	]
}