{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_OPEN","val":1.5,"calc":"mult"},
		{"id":"PARAM_EYE_R_OPEN","val":1.5,"calc":"mult"},
		{"id":"PARAM_EYE_BALL_Y","val":-0.03},
		{"id":"PARAM_BROW_L_ANGLE","val":-0.83},
		{"id":"PARAM_BROW_R_ANGLE","val":-0.83},
		{"id":"PARAM_BROW_L_FORM","val":-0.68},
		{"id":"PARAM_BROW_R_FORM","val":-0.68},
		{"id":"PARAM_MOUTH_FORM_02","val":0.14}
	]
}