{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_BROW_L_Y","val":-0.15},
		{"id":"PARAM_BROW_R_Y","val":-0.15},
		{"id":"PARAM_BROW_L_X","val":-0.82},
		{"id":"PARAM_BROW_R_X","val":-0.82},
		{"id":"PARAM_BROW_L_ANGLE","val":-0.63},
		{"id":"PARAM_BROW_R_ANGLE","val":-0.63},
		{"id":"PARAM_BROW_L_FORM","val":-0.83},
		{"id":"PARAM_BROW_R_FORM","val":-0.8},
		{"id":"PARAM_MOUTH_FORM_01","val":-0.2,"def":-0.5}
	]
}