{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_OPEN","val":0.94,"calc":"mult"},
		{"id":"PARAM_EYE_R_OPEN","val":0.94,"calc":"mult"},
		{"id":"PARAM_BROW_L_Y","val":-0.7},
		{"id":"PARAM_BROW_R_Y","val":-0.71},
		{"id":"PARAM_BROW_L_ANGLE","val":-0.57},
		{"id":"PARAM_BROW_R_ANGLE","val":-0.57},
		{"id":"PARAM_BROW_L_FORM","val":-0.71},
		{"id":"PARAM_BROW_R_FORM","val":-0.71},
		{"id":"PARAM_MOUTH_FORM_01","val":0.49,"def":-0.5}
	]
}