{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_OPEN","val":0,"calc":"mult"},
		{"id":"PARAM_EYE_L_SMILE","val":1},
		{"id":"PARAM_EYE_R_OPEN","val":0,"calc":"mult"},
		{"id":"PARAM_EYE_R_SMILE","val":1},
		{"id":"PARAM_BROW_L_Y","val":-0.1},
		{"id":"PARAM_BROW_R_Y","val":-0.11},
		{"id":"PARAM_BROW_L_FORM","val":-1},
		{"id":"PARAM_BROW_R_FORM","val":-1},
		{"id":"PARAM_MOUTH_FORM_01","val":1,"def":-0.5}
	]
}