{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_FORM","val":0.44},
		{"id":"PARAM_TEAR","val":0.5},
		{"id":"PARAM_BROW_L_ANGLE","val":0.12},
		{"id":"PARAM_BROW_R_ANGLE","val":0.11},
		{"id":"PARAM_BROW_L_FORM","val":-0.5},
		{"id":"PARAM_BROW_R_FORM","val":-0.5},
		{"id":"PARAM_EYE_R_DOUBLE","val":-0.27},
		{"id":"PARAM_EYE_L_DOUBLE","val":-0.26},
		{"id":"PARAM_MOUTH_FORM_01","val":-1,"def":1}
	]
}