{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_OPEN","val":0.93,"calc":"mult"},
		{"id":"PARAM_EYE_L_SMILE","val":1},
		{"id":"PARAM_EYE_R_OPEN","val":0.92,"calc":"mult"},
		{"id":"PARAM_EYE_R_SMILE","val":1},
		{"id":"PARAM_EYELID","val":-0.3},
		{"id":"PARAM_EYE_HIGHLIGHT","val":0.46},
		{"id":"PARAM_MOUTH_FORM_01","val":1},
		{"id":"PARAM_MOUTH_SCALE","val":-0.5}
	]
}